apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-app
        image: ghcr.io/veerendra1233/my-app:dadb2ee571375d75cda04b05c7158f3ca38278f1
        ports:
        - containerPort: 80
