apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-app
        image: ghcr.io/veerendra1233/my-app:42fc1a0fc7c6373487402a0df84bedfb5ffbce42
        ports:
        - containerPort: 80
