apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-app
        image: ghcr.io/veerendra1233/my-app:97e293b358e1384b45b3c40d3905e733d5f3ab48
        ports:
        - containerPort: 80
