apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
      - name: go-service
        image: ghcr.io/veerendra1233/go-service:eaccd4018debd4eba2ada0646b53e6cf7e633a9d
        ports:
        - containerPort: 8080
